language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VER=3.6
  - os: osx
    language: generic
    env: PYTHON_VER=3.7
  - os: linux
    python: 3.6
    env: PYTHON_VER=3.6
  - os: linux
    python: 3.7
    env: PYTHON_VER=3.7
env:
  global:
    - OE_LICENSE="$HOME/oe_license.txt"
before_install:
- openssl aes-256-cbc -K $encrypted_c469bd55e683_key -iv $encrypted_c469bd55e683_iv
  -in oe_license.txt.enc -out $OE_LICENSE -d
- uname -a
- df -h
- ulimit -a
- source devtools/travis-ci/before_install.sh
- python -V
install:
- python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
- conda activate test
- python setup.py develop --no-deps
script:
- pytest -v --cov=propertyestimator propertyestimator/tests/
notifications:
  email: false
after_success:
- codecov
