name: evaluator
channels:
    - conda-forge
dependencies:
    # Base depends
    - python =3.7
    - setuptools
    - pip

    # Sphinx specific
    - sphinx >=4.5,<5
    - nbsphinx
    - sphinx-notfound-page
    - sphinxcontrib-bibtex
    - pandoc
    - ipython

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - networkx
    - pint >=0.10.1
    - uncertainties

    - pip:
      - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
