name: evaluator
channels:
    - conda-forge
dependencies:
    # Base depends
    - python =3.7
    - setuptools

    # Sphinx specific
    - nbsphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - pandoc
    - ipython

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - networkx
    - pint >=0.10.1
    - uncertainties
