name: propertyestimator
channels:
    - omnia
    - conda-forge
dependencies:
    # Base depends
    - python ==3.6
    - setuptools

    # Sphinx specific
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1

    # Standard dependencies
    - openforcefield
    - numpy
    - pandas
    - lxml
    - icu 58*  # This is a lxml dependency but sometimes conda installs version 56
    - openmm
    - packmol
    - pymbar
    - mdtraj
    - dask
    - tornado
    - uncertainties

    - pip:
        - sphinx_rtd_theme
