name: lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --check-only openff
          isort --check-only integration-tests

      - name: Run black
        run: |
          black openff --check
          black integration-tests --check

      - name: Run flake8
        run: |
          flake8 openff
          flake8 integration-tests
